import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Floob DAO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-screen h-screen">
        <div className="flex items-center justify-center h-full">
          <div className="max-w-lg">
            <h1 className="text-2xl">ALL HAIL INTERGALACTIC FLOOB</h1>
            <p>
              The year is 2429, human civilization has been consumed by the
              Fl00b bots.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
